version: '3'

services:
  mysqldb:
    image: mysql:8.0.32
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - clinic_app

  springbootproject:
    build: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/clinic_app?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=root
      - spring.jpa.hibernate.ddl-auto=update
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
      - spring.jpa.show-sql=true
      - spring.jpa.properties.hibernate.format_sql=true
      - spring.jpa.properties.hibernate.use_sql_comments=true
    networks:
      - clinic_app

networks:
  clinic_app:
